CREATE TABLE Users(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);
CREATE TABLE Tasks(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Subject TEXT NOT NULL,
    Description TEXT NULL,
    AssigneeId INTEGER NULL,
    FOREIGN KEY(AssigneeId) REFERENCES Users(Id)
);
INSERT INTO Users(Name) VALUES('User0');
INSERT INTO Users(Name) VALUES('User1');